### ISSUE TITLE
Broken Modeling And Simulation Course Links

### ISSUE THREAD

**Issue by Badranh** [J-Mrad/J-Mrad.github.io#1]
There is a typo in the course code I3344 is wrong in links
ex:
Broken Link: https://j-mrad.github.io/data/I3334/Summaries/1.pdf
**should be**
Working Link: https://j-mrad.github.io/data/I3344/Summaries/1.pdf

**Comment by J-Mrad** [comment]
Fixed 👍 
Thanks for reporting it
